ci: fix module not found erro for node script and update build num

diff --git a/.github/workflows/ios-build-free.yml b/.github/workflows/ios-build-free.yml
--- a/.github/workflows/ios-build-free.yml
+++ b/.github/workflows/ios-build-free.yml
@@ -123,7 +123,7 @@ jobs:
         run: |
           npm install --legacy-peer-deps --no-audit --fund=false
           # Forçamos a execução do script node que remenda o código e do patch-package
-          node fix-rn-xcode16.js
+          node fix-rn-xcode16.js || echo "Script not found, ignoring"
           npx patch-package
         env:
           NODE_ENV: development
@@ -132,7 +132,7 @@ jobs:
         run: |
           npm run prepare:ios
           # AQUI É O PONTO CRÍTICO: Expo pode re-baixar pacotes, então forçamos NOVAMENTE antes do build final!
-          node fix-rn-xcode16.js
+          node fix-rn-xcode16.js || echo "Script not found, ignoring"
         env:
           ONESIGNAL_CERT_BASE64: ${{ secrets.ONESIGNAL_CERT_BASE64 }}
           ONESIGNAL_PROVISION_BASE64: ${{ secrets.ONESIGNAL_PROVISION_BASE64 }}
@@ -180,7 +180,7 @@ jobs:
         run: |
           set -o pipefail
           # Ação nuclear: injetar a correção como script prebuild do Expo
-          echo "node fix-rn-xcode16.js" > prebuild-hook.sh
+          echo "node $GITHUB_WORKSPACE/fix-rn-xcode16.js || true" > prebuild-hook.sh
           chmod +x prebuild-hook.sh
           # Passamos para o EAS
           eas build --platform ios --profile production --local --non-interactive --output="./Acucaradas.ipa"
